apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-6
  labels:
    env: test-env
spec:
  containers:
    - name: nginx-test
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  tolerations:
    - key: "gpu"
      operator: "Exists"
      effect: "NoSchedule"
# Commands for tainting and untainting a node
#  kubectl taint nodes ip-192-168-28-230.eu-west-1.compute.internal gpu=true:NoSchedule
#  kubectl describe node ip-192-168-28-230.eu-west-1.compute.internal
#  kubectl apply -f taints-tolerations.yaml
#  kubectl taint nodes ip-192-168-28-230.eu-west-1.compute.internal gpu=false:NoSchedule
#  kubectl taint nodes ip-192-168-42-157.eu-west-1.compute.internal gpu:false:NoSchedule
#  kubectl taint nodes ip-192-168-42-157.eu-west-1.compute.internal gpu=false:NoSchedule
#  kubectl apply -f taints-tolerations.yaml
#  kubectl taint nodes ip-192-168-28-230.eu-west-1.compute.internal gpu=true:NoSchedule-
#  kubectl apply -f taints-tolerations.yaml
#  kubectl taint nodes ip-192-168-28-230.eu-west-1.compute.internal gpu=true:NoExecute
#  kubectl taint nodes ip-192-168-28-230.eu-west-1.compute.internal gpu=true:NoExecute-
