- name: Install git on servers
  hosts: all
  become: true
  tasks:
    - name: Clone a repo
      git:
        repo: https://github.com/kushaggarwal/Devops-770
        dest: /home/ubuntu/repo
        clone: yes
        update: yes
